# -*- coding: utf-8 -*-
"""Random.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bl93A91jVsOEX9qB0b0w_aON518DWu24
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

file=np.loadtxt("finaltrail2.txt")
print(file)

x1=file[:, 0]
y1=file[:,2]
y2=file[:,5]
y3=file[:,8]
plt.xlabel('Number of Buyers')
plt.ylabel('Total payment')
plt.title('Buyers Payment in QUAD, McAfee and PPM')
width = 1.20
plt.bar(x1,y2,
        width = width, 
        label='QUAD',fill=False, hatch='///',facecolor='lightgray',edgecolor='darkgreen')
plt.bar(x1+width,y1,
        width = width, 
        label='McAfee',fill=False,hatch='....',facecolor='lightgray',edgecolor='red')

plt.bar(x1+width+width,y3,
        width = width,
        label='PPM',fill=False, hatch='\\\\\\' ,facecolor='lightgray' ,edgecolor='blue')

plt.legend()
  
plt.show()

x1=file[:, 1]
y1=file[:,3]
y2=file[:,6]
y3=file[:,9]
plt.xlabel('Number of Sellers')
plt.ylabel('Total payment')
plt.title('Sellers Payment in QUAD, McAfee and PPM')
width = 1.20
plt.bar(x1,y2,
        width = width, 
        label='QUAD',fill=False, hatch='///',facecolor='lightgray',edgecolor='darkgreen')
plt.bar(x1+width,y1,
        width = width, 
        label='McAfee',fill=False,hatch='....',facecolor='lightgray',edgecolor='red')

plt.bar(x1+width+width,y3,
        width = width,
        label='PPM',fill=False, hatch='\\\\\\' ,facecolor='lightgray' ,edgecolor='blue')
plt.legend()
  
plt.show()

x1=file[:,11]
y1=file[:,12]
y2=file[:,13]
y3=file[:,14]
plt.plot(x1,y1,label="McAfee")
plt.plot(x1,y2,label="QUAD")
plt.plot(x1,y3,label="PPM")
plt.xlabel('Number of traders')
plt.ylabel('GFT Value')
plt.legend()
plt.show()


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

file2=np.loadtxt("largedata1.txt")
print(file2)

x1=file2[:, 0]
y1=file2[:,2]
y2=file2[:,5]
y3=file2[:,8]
plt.xlabel('Number of Buyers')
plt.ylabel('Total payment')
plt.title('Buyers Payment in QUAD, McAfee and PPM')
width =20.20
plt.bar(x1,y2,
        width = width, 
        label='QUAD',fill=False, hatch='///',facecolor='lightgray',edgecolor='darkgreen')
plt.bar(x1+width,y1,
        width = width, 
        label='McAfee',fill=False,hatch='....',facecolor='lightgray',edgecolor='red')

plt.bar(x1+width+width,y3,
        width = width,
        label='PPM',fill=False, hatch='\\\\\\' ,facecolor='lightgray' ,edgecolor='blue')
plt.legend()
  
plt.show()

x1=file2[:, 1]
y1=file2[:,3]
y2=file2[:,6]
y3=file2[:,9]
plt.xlabel('Number of Sellers')
plt.ylabel('Total payment')
plt.title('Sellers Payment in QUAD, McAfee and PPM')
width = 20.20
plt.bar(x1,y2,
        width = width, 
        label='QUAD',fill=False, hatch='///',facecolor='lightgray',edgecolor='darkgreen')
plt.bar(x1+width,y1,
        width = width, 
        label='McAfee',fill=False,hatch='....',facecolor='lightgray',edgecolor='red')

plt.bar(x1+width+width,y3,
        width = width,
        label='PPM',fill=False, hatch='\\\\\\' ,facecolor='lightgray' ,edgecolor='blue')
plt.legend()
  
plt.show()

x1=file2[:,11]
y1=file2[:,12]
y2=file2[:,13]
y3=file2[:,14]
plt.plot(x1,y1,label="McAfee")
plt.plot(x1,y2,label="QUAD")
plt.plot(x1,y3,label="PPM")
plt.xlabel('Number of traders')
plt.ylabel('GFT Value')
plt.legend()
plt.show()